version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Australia/Adelaide
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'deps'
    groups:
      dev-dependencies:
        patterns: ['*']
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: Australia/Adelaide
    commit-message:
      prefix: 'ci'
    groups:
      actions:
        patterns: ['*']
